apiVersion: v1
kind: Secret
metadata:
  name: knowledge-base-secrets
type: Opaque
data:
  # Base64 encoded secrets
  # Example: echo -n "your-api-key" | base64
  KB_GENERATION_API_KEY: "" # Replace with base64 encoded API key
  KB_EMBEDDING_OPENAI_API_KEY: "" # Replace with base64 encoded API key
  KB_STORAGE_NOTION_API_KEY: "" # Replace with base64 encoded API key
  KB_STORAGE_NOTION_DATABASE_ID: "" # Replace with base64 encoded database ID